# main.yml

name: Build Electron App For Win

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: build and release electron app
    runs-on: ${{ matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4.2.2

      - name: Install Node.js
        uses: actions/setup-node@v4.2.0

      - name: npm install
        run: |
          npm install

      - name: cleanup artifacts in dist
        if: matrix.os == 'windows-latest'
        run: |
          npx rimraf "dist/!(*.exe)"
          npx rimraf "dist/!(*.msi)"

      - name: build windows app
        if: matrix.os == 'windows-latest'
        run: |
          npm run dist:win

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: |
            dist/*.exe
            dist/*.msi

      - name: release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.exe
            dist/*.msi
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
